name: .NET

# Trigger this workflow on a push, or pull request to the master or develop branch
on:
  push:
  pull_request:
    branches: [master, develop]
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.x', '7.x'] # Specify the .NET versions you want to test against
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build
        run: ./build.sh Compile
      - name: Test
        run: ./build.sh Test

  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.x', '7.x'] # Specify the .NET versions you want to test against
    env:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
    needs: build
    # Publish for a tag starting with v.
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Deploy
        run: ./build.sh DeployNuGet
