name: .NET

# Trigger this workflow on a push, or pull request to the master or develop branch
on:
  push:
  pull_request:
    branches: [master, develop]
    paths-ignore:
      - "README.md"

env:
  DOTNET_VERSION: "7.0.x" # The .NET SDK version to use

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true
      - name: Build
        run: ./build.sh Compile
      - name: Test
        run: ./build.sh Test

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    needs: build
    # Publish for a tag starting with v.
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Deploy
        run: dotnet nuget push "Snowberry.IO/bin/Release/*.nupkg" --api-key ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
